language: node_js
node_js:
- '11'
addons:
  chrome: stable
before_script:
- cd uberpage
- npm install
- npm install -g codacy-coverage
script:
- npm run lint
- CI=true npm test -- --coverage
- CI=true npm run build
after_script:
- codacy-coverage < coverage/lcov.info
notifications:
  email:
    on_failure: change
    on_success: change
deploy:
  provider: releases
  api_key:
    secure: ANlzfolVIa2EOCMpIvrvnh35/RzfJ4d0C7ddezXXkHS50RoscnLQ2+SBYvt7FBW5JtMFmZKUJ1KWjWzXx0maJcLuMMSIOPYQ5tW2U+XetzElBLDLR8DKLxQeEpB8RnFptHnuJGCmaPZkmbVXP0i9ZEZJyB2a1VNEeegg0+S1cp36dEmduOHgEaF3SOApdyxpkZMbtgXYkS2Yh0M+6790bAGgxJ0IGWD1CHwuCcQy8OXhJKQfgUBZLDQvm9EuvbnzWv48Glnvgq5pqVlGjV6UMFoyhQH/YghWwvaazE1vCrr6/dGXO1akjaoMVtX/LKX8h5ZwKV9YwbHrXiQd8kE3obFtE2uIdUR33hhHNx0m3JT7/9Ln/lFo9Q5qzFVgonOtt+PfPYMY2BD9UYpkcvjXYUTSQghIcAJerkpkkdAY3hMjZQUHcH6sEp46A0SYF2F2d8hrR7wMQLkWKjnaS8ThuNfgnilTEjW+H6HoXPqKUl2H+RHS5OdV0uw0atbaTT5p8/hDa0nnOsMc0pqLNPHEh3IadPqKyJAPUYCciMWFgfRZpDiDekjiOyFv2cSAXYs98ARPhAmj6NspxE5i6rIiU7hegL0hQ4QQxzPteWQ5tq+Ldnjj/ezMbGGZ+gXbqFpSDh9v2S9m3a26pPBF3bCyNaURn/qLtRF6wXIXtIsefrg=
  on:
    repo: StegSchreck/uberpage
    tags: true
